In [16]:
#import numpy 
import numpy as np

#creating an array using numpy arange
arr = np.arange(2,50,3)

#printing the array
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [27]:
#import numpy
import numpy as np

#creating two empty list
lst_1 = []
lst_2 = []

#Getting values for lst_1
for i in range(5):
    x = int(input("\n Enter the value for lst_1: "))
    lst_1.append(x)
    
#Getting values for lst_2
for i in range(5):
    x = int(input("\n Enter the value for the lst_2: "))
    lst_2.append(x)
    
#converting into array
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

#concatenating the array
arr = np.concatenate((arr_1,arr_2))
print("\n Value of concatenated array:",arr)

#sorting the conccatenated array
sortArr = np.sort(arr)
print("\n sorted array:",sortArr )



 Enter the value for lst_1: 2

 Enter the value for lst_1: 4

 Enter the value for lst_1: 5

 Enter the value for lst_1: 7

 Enter the value for lst_1: 5

 Enter the value for the lst_2: 9

 Enter the value for the lst_2: 3

 Enter the value for the lst_2: 5

 Enter the value for the lst_2: 2

 Enter the value for the lst_2: 1

 Value of concatenated array: [2 4 5 7 5 9 3 5 2 1]

 sorted array: [1 2 2 3 4 5 5 5 7 9]


In [18]:
 #importing numpy
import numpy as np    

#creating a 2d array
arr = np.array([[4,6,7],[2,8,9],[3,4,5]])

#printing array dimensions
print("\n Dimensions of array: ", arr.ndim)

#printing array size
print("\n Size of the array: ", arr.size)


 Dimensions of array:  2

 Size of the array:  9


In [20]:
#importing numpy 
import numpy as np

#creating a 1d array
arr = np.arange(10)
print("\n shape of array:",arr.shape)

#converting using newaxis in row dimensions
row_arr = arr[np.newaxis, :]
print("\n shape of 2d array in row major: ",row_arr.shape)

#converting using newaxis in coloumn dimensions
col_arr = arr[:, np.newaxis]
print("\n shape of 2d array in column major: ", col_arr.shape)




 shape of array: (10,)

 shape of 2d array in row major:  (1, 10)

 shape of 2d array in column major:  (10, 1)


In [22]:
#importing numpy
import numpy as np

#creating a 1d array
arr = np.arange(10)
print("\n shape of array:",arr.shape)

#converting using newaxis in row dimensions
row_arr = np.expand_dims(arr,axis=0)
print("\n Shape of 2d array in row major: ", row_arr.shape)

#converting using newaxis in column dimensions
col_arr = np.expand_dims(arr,axis=1)
print("\n Shape of 2nd array in column major: ",col_arr.shape)


 shape of array: (10,)

 Shape of 2d array in row major:  (1, 10)

 Shape of 2nd array in column major:  (10, 1)


In [25]:
#importing numpy
import numpy as np

#creating a array with sqauare values
arr_1 = np.square([1,2,3,4,5])
arr_2 = np.square([6,7,8,9,10])

#stacking and printing the value
print("\nHorizontal append: ",np.hstack((arr_1,arr_2)))
print("\nVertical append: ",np.vstack((arr_1,arr_2)))


Horizontal append:  [  1   4   9  16  25  36  49  64  81 100]

Vertical append:  [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


In [26]:
#importing numpy
import numpy as np

#creating an array 
arr_1 = np.array([1,5,7,3,8,2,4,3,3,2,5,6,7,9,8,10,14,7,9])

#getting unique characters and its count
unique, counts = np.unique(arr_1,return_counts=True)

#making a unique item
arr = np.asarray((unique,counts)).T

print(arr)

[[ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  1]
 [ 5  2]
 [ 6  1]
 [ 7  3]
 [ 8  2]
 [ 9  2]
 [10  1]
 [14  1]]
